article/urls.py
from django.contrib import admin
from django.urls import path
from .import views


app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addarticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),

    
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = "index"),
    path('about/',views.about,name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar" )
    title = models.CharField(max_length= 50,verbose_name = "Başlık")
    content = RichTextField()
    created_Date = models.DateTimeField(auto_now_add=True,verbose_name = "Oluşturulma Tarihi")
    article_image = models.FileField(blank = True, null = True,verbose_name ="Makaleye Fotoğraf Ekleyin")

    def __str__(self):
        return self.title
        
    
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE, verbose_name = "Makale",related_name = "comments")
    comment_author = models.CharField(max_length=50,verbose_name="İsim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.comment_content
    

article/forms.py
from django import forms
from .models import Article



class ArticleForms(forms.ModelForm):
    
    class Meta:

        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForms
from .models import Article, Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.


def articles(request):

    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles" : articles})
    
    articles = Article.objects.all()

    context = {
        
        "articles":articles,
        
        
        
        }

    return render(request,"articles.html",context)



def index(request):
    context = {

        "numbers":[1,2,3,4,5,6]
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")
    
def detail(request,id):
    return HttpResponse("Detail:"+ str(id))
@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    
    context = { 
        "articles": articles


    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addarticle(request):
    
    form = ArticleForms(request.POST or None,request.FILES or None)
    
    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()


        messages.success(request,"Makale Başarıyla Oluşturuldu")
        return redirect("article:dashboard")

    



    return render(request,"addarticle.html", {"form": form})


def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)

    comments = article.comments.all()
   
    return render( request,"detail.html", {"article":article, "comments":comments})
@login_required(login_url = "user:login")

def updateArticle(request,id):
   
    article = get_object_or_404(Article,id = id)
    form = ArticleForms(request.POST or None,request.FILES or None, instance = article) 
    
    if form.is_valid():
        article = form.save(commit=False)

        article.author = request.user
        article.save()


        messages.success(request,"Makale Başarıyla Güncellendi")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form": form})
    
@login_required
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()
    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("article:dashboard")


def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")


        newComment = Comment(comment_author= comment_author, comment_content= comment_content)

        newComment.article = article

        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}


{% block body %}


<h3>Hakkımızda</h3>
<hr>
Herkese Merhaba, ben Erman Göllü.
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}


<hr>
<div class="row">
  <div class="col-md-6 offset-md-3">
  
  <h3>Makale Oluştur
  </h3>
   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form |crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Makale Ekle</button>

    </form>

 
  
  
  </div>
  

</div>



{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}


    <div class="row">

        <div class="col-md-10 offset-md-3"> 
                <div class="col-lg-8">
                <h3>Makaleler</h3>
                <hr>
                </div>
        </div>

        <div class="col-md-10 offset-md-3"> 
                <div class="col-lg-8">
                <form >
                        {% csrf_token %}
                        <input type="text" name= "keyword" class = "input-sm">
                        <button type = "submit" class = "btn btn-danger" >Ara</button>
                

                </form>
                </div>

        </div>

    </div>
    

    


    {% if articles %}

            {% for article in articles  %}

        <div class="row">
                <div class="col-md-10 offset-md-3">

                        <!-- Post Content Column -->
                        <div class="col-lg-8">

                                <!-- Title -->
                        <a href="/articles/article/{{article.id}}"><h2 class="mt-4">{{article.title}}</h2> </a> 

                                <!-- Author -->
                                <p class="lead">
                                
                                {{article.author.username}} tarafından yayınlandı.
                                </p>

                                <hr>

                                <!-- Date/Time -->
                                <p>{{article.created_Date}}</p>

                                <hr>

                                <!-- Preview Image -->
                                

                                {% if article.article_image. %}
                                <a href="/articles/article/{{article.id}}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a> 
                                {% endif %}

                                <hr>

                                <!-- Post Content -->
                                <p class="lead">
                                {{article.content |safe |truncatewords:50}}
                                
                                <a style = "float : right;" href="/articles/article/{{article.id}}" class = "btn btn-danger" >Devamını Oku</a>

                                <hr>

                                </div>
                </div>
        </div>




            {% endfor %}


    {% else %}
            <div class = "alert alert-danger">
            Makale Bulunamadı.
            </div>
            
    {% endif %}



{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}


<h3>Kontrol Paneli</h3>
<hr>

<p> 

    Hoşgeldiniz, <small>{{request.user.username}}</small>

</p>
<hr>


<a class="btn btn-danger" href="/articles/addarticle/">Makale Oluştur </a>
<hr>  

{% if articles %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Başlık Alanı</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
  
      <tr>
          <th scope="row">{{article.id}}</th>
          <td><a href="/articles/article/{{article.id}}">{{article.title}} </a></td>
          <td>{{article.author.username}}</td>
          <td>{{article.created_Date}}</td>
          <td><a href="/articles/update/{{article.id}}" class = "btn btn-danger">Güncelle</a></td>
          <td><a href="/articles/delete/{{article.id}}" class = "btn btn-danger">Sil</a></td>
  
  
      </tr>
      {% endfor %}
     

    </tbody>
  </table>
   

{% else %}

<div class = "alert alert-danger" > 
    Henüz bir makaleniz bulunmuyor. 


</div>
  
{% endif %}





{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}
<hr>

                <div class="row">

                <!-- Post Content Column -->
                <div class="col-lg-8">

                  <!-- Title -->
                  <h3 class="mt-4">{{article.title}}</h3>

                  <!-- Author -->
                  <p class="lead">
                    by
                    {{article.author.username}}
                  </p>

                  <hr>

                  <!-- Date/Time -->
                  <p>{{article.created_Date}}</p>

                  <hr>

                  <!-- Preview Image -->
                  

                  {% if article.article_image %}
                  <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                  {% endif %}

                  <hr>

                  <!-- Post Content -->
                  <p class="lead">
                  {{article.content |safe}}
                  
                  <hr>

                  <h4> Yorumlar </h4>
                  <hr>


                  {% if comments %}

                  {% for comment in comments  %}
                  
                  

                <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}</h5>
            {{comment.comment_date}} <br></br>
            
           {{comment.comment_content}}
          </div>
        </div>

                {% endfor %}


                  
                  {% else %}
                  <div class = "alert alert-danger">
                  Bu makaleye herhangi bir yorum yazılmamış,ilk yorum yapan siz olun..
                  </div>
                  {% endif %}

                  
                  
                  
                  <!-- Comments Form -->
<div class="card my-4">
<h5 class="card-header">Yorum Ekle:</h5>
    <div class="card-body">
              

    <form method = "post" action="{% url 'article:comment' article.id %}">
    {% csrf_token %}
    
        <div class="form-group">
            <label for="formGroupExampleInput">İsim</label>
            <input name="comment_author"  type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Girin">
        </div>
                                              
        <div class="form-group">
                      <label for="formGroupExampleInput">Yorum</label>
        <textarea name= "comment_content" class="form-control" id="" rows="3"></textarea> 
        </div>




        <button type="submit" class="btn btn-danger">Ekle</button>     
    </form>   
      
    </div>
</div>

      

    

      

{% endblock body %}

templates/index.html
{% extends 'layout.html' %}

    {% block body %}

  <div class = "jumbotron text-center"> 
      <h3>Yazılım Bilimi Bloğuna Hoşgeldiniz</h3>
      <p>Bu blogda gelişririciler olarak blog yazılarını ve düşüncelerinizi paylaşabilirsiniz.</p>


  </div> 



<p>

    {% if request.user.is_authenticated %}
            Giriş Yapılmış, {{request.user.username}}
    {% else %}
            Giriş Yapılmamış
    {% endif %}


</p>
 
  
  
  <ul>

  {% endblock body %}
    

templates/layout.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <title>ErmanG</title>
</head>
<body>
        
    
    {% include "includes/navbar.html" %}

  
    
    <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">

    {% if messages %}
 
                {% for message in messages %}


              {% if message.tags == "info" %}
              <div class="alert alert-danger{{ message.info }}" >{{ message }}</div>
              {% else %}
                <div class="alert alert-{{ message.tags }}" >{{ message }}</div>
              {% endif %}


            
            

   
    {% endfor %}



{% endif %}
    


            {% block body %}
              
            {% endblock body %}


        </div>



        

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>


    
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}


<hr>
<div class="row">
  <div class="col-md-6 offset-md-3">
  
  <h3>Giriş Yap</h3>
  <form method="post">
        {% csrf_token %}

        {{form |crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Giriş Yap</button>

        </form>
  
  </div>
  

</div>



        {% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}


<hr>
<div class="row">
  <div class="col-md-6 offset-md-3">
  
  <h3>Kayıt Ol</h3>
  <hr>
  <form method="POST">
        {% csrf_token %}

        {{form |crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Giriş Yap</button>

        </form>
  
  </div>
  

</div>


></form>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}


<hr>
<div class="row">
  <div class="col-md-6 offset-md-3">
  
  <h3>Makale Güncelle</h3>
   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form |crispy}}
        <br>
        <button type = "submit" class = "btn btn-danger">Makale Güncelle</button>

    </form>

 
  
  
  </div>
  

</div>



{% endblock body %}